geertmeersman/robonect

custom_components/robonect/client.py
=> Timer fix when mowing

custom_components/robonect/__init__.py, custom_components/robonect/client.py, custom_components/robonect/config_flow.py, custom_components/robonect/const.py, custom_components/robonect/models.py, custom_components/robonect/sensor.py, custom_components/robonect/translations/de.json, custom_components/robonect/translations/en.json, custom_components/robonect/translations/nl.json, custom_components/robonect/utils.py
=> Device split and config flow options added for sensor tracking

custom_components/robonect/const.py
=> Don't bypass sleep :-)

custom_components/robonect/client.py
=> Reverting to 1 device

custom_components/robonect/client.py, custom_components/robonect/entity.py
=> Debug line fix & device renaming

README.md
=> docs: lovelace mower card

README.md
=> docs: lovelace example details on cards, references #28

README.md
=> docs: lovelace EOD correction in card

README.md
=> docs: TOC & daily mowing time sensor

custom_components/robonect/binary_sensor.py, custom_components/robonect/button.py, custom_components/robonect/sensor.py, custom_components/robonect/utils.py
=> fix: convert attribute values

.github/workflows/bump_version_and_prerelease.yml
=> fix: Beta workflow

README.md
=> docs: REST/MQTT priority and update explained

custom_components/robonect/__init__.py
=> fix: RuntimeWarning: coroutine 'RobonectClient.state' was never awaited

.github/workflows/bump_version_and_prerelease.yml
=> fix: Change bump workflow names

.github/labels.yml, .github/workflows/pr-checker.yml, .github/workflows/validate.yml
=> refactor: workflow names

.github/workflows/validate.yml
=> refactor: only validate custom_component changes

custom_components/robonect/config_flow.py, custom_components/robonect/manifest.json
=> fix: bump aiorobonect to 0.2.4

custom_components/robonect/manifest.json
=> fix: bump aiorobonect to 0.2.5

custom_components/robonect/manifest.json
=> fix: add jsonpath dependency

custom_components/robonect/entity.py
=> fix: HA 2023.7 release fix, references #56

README.md
=> docs: lovelace card to start the mower again when stopped

README.md
It took me a few minutes to understand that the credentials used to access the REST API were the same as for accessing the web UI. I've searched in the settings, the robonect forum, and so on...
=> doc: Document REST API username/password

custom_components/robonect/utils.py
=> fix: hex2weekdays, D400 First line should end with a period

README.md
=> docs: finally merged into HACS default

custom_components/robonect/services.yaml
=> fix: names added for service fields

custom_components/robonect/manifest.json
=> deps: bump aiorobonect

custom_components/robonect/__init__.py, custom_components/robonect/definitions.py, custom_components/robonect/manifest.json
=> feat: weather service added

custom_components/robonect/switch.py
=> fix: switch error removed when only mqtt is enabled

.github/workflows/bump_version_and_release.yml
=> fix: move release zip

custom_components/robonect/config_flow.py, custom_components/robonect/translations/de.json, custom_components/robonect/translations/en.json, custom_components/robonect/translations/fr.json, custom_components/robonect/translations/nl.json
=> fix: config flow fix

custom_components/robonect/__init__.py
=> fix: ignore connection issues

custom_components/robonect/definitions.py
=> fix: Deprecated units, references #121

custom_components/robonect/icons.json
=> fix: icons.json for services/hassfest

custom_components/robonect/binary_sensor.py
=> fix: state check for binary sensor

custom_components/robonect/utils.py
=> fix: improvement for wifi % calculation

custom_components/robonect/__init__.py, custom_components/robonect/config_flow.py
=> fix: replace aiohttp by httpx, fixes #152

custom_components/robonect/manifest.json
=> fix: take https scheme into account

custom_components/robonect/manifest.json
=> fix: only switch to https scheme on a redirect (3xx) or connection error

custom_components/robonect/manifest.json
=> fix: throw requesterror when response is none, bump aiorobonect

custom_components/robonect/manifest.json
=> fix: move warnings on requesterrors to debug, bump aiorobonect

custom_components/robonect/manifest.json
=> fix: bump aiorobonect to catch incorrect robonect json

README.md
=> docs: yaml markdown

.github/workflows/validate.yml, custom_components/robonect/__init__.py, custom_components/robonect/utils.py
=> fix: blocking call for timezone fetching, references #171

.github/workflows/validate.yml
=> fix: concurrency for validat workflow

README.md
=> docs: Sensor templates for lovelace
